token_create:
  path: /token/create
  controller: App\Controller\TokenController::create
  defaults:
    authentication: false
    validator: App\Validator\Token\TokenCreateValidator

token_identify:
  path: /token/identify
  controller: App\Controller\TokenController::identify
  defaults:
    validator: App\Validator\Token\TokenCreateValidator